type CatalogEntity = { [key: string]: unknown };
type EntityConstructor = new (...args: unknown[]) => CatalogEntity;
type HaveTech = (id: string, level: number) => unknown;

type EntityCatalogDependencies = {
  classes: Record<string, EntityConstructor>;
  getHaveTech: () => HaveTech;
  setResources: (resources: Record<string, CatalogEntity>) => void;
};

export function createEntityCatalogs({
  classes,
  getHaveTech,
  setResources,
}: EntityCatalogDependencies) {
  const {
    Action,
    BasicJob,
    BeltSupport,
    CityAction,
    CraftingJob,
    ElectrolysisSupport,
    Job,
    ModalAction,
    Morale,
    Pillar,
    Population,
    Power,
    PrestigeResource,
    Project,
    Resource,
    ResourceAction,
    SoulGem,
    SpaceDock,
    Supply,
    Support,
    Thrall,
    Troops,
    WomlingsSupport,
  } = classes;
  const haveTech: HaveTech = (id, level) => getHaveTech()(id, level);
  const resources = {
    // Resources order follow game order, and used to initialize priorities
    // Evolution resources
    RNA: new Resource("RNA", "RNA"),
    DNA: new Resource("DNA", "DNA"),

    // Base resources
    Money: new Resource("Money", "Money"),
    Population: new Population("Population", "Population"), // We can't store the full elementId because we don't know the name of the population node until later
    Slave: new Resource("Slave", "Slave"),
    Mana: new Resource("Mana", "Mana"),
    Energy: new Resource("Energy", "Energy"),
    Sus: new Resource("Suspicion", "Sus"),
    Authority: new Resource("Authority", "Authority"),
    Knowledge: new Resource("Knowledge", "Knowledge"),
    Omniscience: new Resource("Omniscience", "Omniscience"),
    Zen: new Resource("Zen", "Zen"),
    Crates: new Resource("Crates", "Crates"),
    Containers: new Resource("Containers", "Containers"),

    // Basic resources (can trade for these)
    Food: new Resource("Food", "Food", { tradable: true }),
    Lumber: new Resource("Lumber", "Lumber", { tradable: true }),
    Chrysotile: new Resource("Chrysotile", "Chrysotile", { tradable: true }),
    Stone: new Resource("Stone", "Stone", { tradable: true }),
    Crystal: new Resource("Crystal", "Crystal", { tradable: true }),
    Furs: new Resource("Furs", "Furs", { tradable: true }),
    Copper: new Resource("Copper", "Copper", { tradable: true }),
    Iron: new Resource("Iron", "Iron", { tradable: true }),
    Aluminium: new Resource("Aluminium", "Aluminium", { tradable: true }),
    Cement: new Resource("Cement", "Cement", { tradable: true }),
    Coal: new Resource("Coal", "Coal", { tradable: true }),
    Oil: new Resource("Oil", "Oil", { tradable: true }),
    Uranium: new Resource("Uranium", "Uranium", { tradable: true }),
    Steel: new Resource("Steel", "Steel", { tradable: true }),
    Titanium: new Resource("Titanium", "Titanium", { tradable: true }),
    Alloy: new Resource("Alloy", "Alloy", { tradable: true }),
    Polymer: new Resource("Polymer", "Polymer", { tradable: true }),
    Iridium: new Resource("Iridium", "Iridium", { tradable: true }),
    Helium_3: new Resource("Helium-3", "Helium_3", { tradable: true }),

    // Advanced resources
    Water: new Resource("Water", "Water"),
    Deuterium: new Resource("Deuterium", "Deuterium"),
    Neutronium: new Resource("Neutronium", "Neutronium"),
    Adamantite: new Resource("Adamantite", "Adamantite"),
    Infernite: new Resource("Infernite", "Infernite"),
    Elerium: new Resource("Elerium", "Elerium"),
    Nano_Tube: new Resource("Nano Tube", "Nano_Tube"),
    Graphene: new Resource("Graphene", "Graphene"),
    Stanene: new Resource("Stanene", "Stanene"),
    Bolognium: new Resource("Bolognium", "Bolognium"),
    Vitreloy: new Resource("Vitreloy", "Vitreloy"),
    Orichalcum: new Resource("Orichalcum", "Orichalcum"),
    Asphodel_Powder: new Resource("Asphodel Powder", "Asphodel_Powder"),
    Elysanite: new Resource("Elysanite", "Elysanite"),
    Unobtainium: new Resource("Unobtainium", "Unobtainium"),
    Materials: new Resource("Materials", "Materials"),

    Horseshoe: new Resource("Horseshoe", "Horseshoe"),
    Nanite: new Resource("Nanite", "Nanite"),
    Genes: new Resource("Genes", "Genes"),
    Soul_Gem: new SoulGem("Soul Gem", "Soul_Gem"),

    // Craftable resources
    Plywood: new Resource("Plywood", "Plywood"),
    Brick: new Resource("Brick", "Brick"),
    Wrought_Iron: new Resource("Wrought Iron", "Wrought_Iron"),
    Sheet_Metal: new Resource("Sheet Metal", "Sheet_Metal"),
    Mythril: new Resource("Mythril", "Mythril"),
    Aerogel: new Resource("Aerogel", "Aerogel"),
    Nanoweave: new Resource("Nanoweave", "Nanoweave"),
    Scarletite: new Resource("Scarletite", "Scarletite"),
    Quantium: new Resource("Quantium", "Quantium"),

    // Special resources
    Corrupt_Gem: new Resource("Corrupt Gem", "Corrupt_Gem"),
    Codex: new Resource("Codex", "Codex"),
    Cipher: new Resource("Encrypted Data", "Cipher"),
    Demonic_Essence: new Resource("Demonic Essence", "Demonic_Essence"),
    Blessed_Essence: new Resource("Blessed Essence", "Blessed_Essence"),

    // Prestige resources
    Blood_Stone: new PrestigeResource("Blood Stone", "Blood_Stone"),
    Artifact: new PrestigeResource("Artifact", "Artifact"),
    Plasmid: new PrestigeResource("Plasmid", "Plasmid"),
    AntiPlasmid: new PrestigeResource("Anti-Plasmid", "AntiPlasmid"),
    Supercoiled: new PrestigeResource("Supercoiled", "Supercoiled"),
    Phage: new PrestigeResource("Phage", "Phage"),
    Dark: new PrestigeResource("Dark", "Dark"),
    Harmony: new PrestigeResource("Harmony", "Harmony"),
    AICore: new PrestigeResource("AI Core", "AICore"),

    // Special not-really-resources-but-we'll-treat-them-like-resources resources
    Troops: new Troops("Troops", "Troops"),
    Supply: new Supply("Supplies", "Supply"),
    Power: new Power("Power", "Power"),
    Morale: new Morale("Morale", "Morale"),
    Thrall: new Thrall("Thrall", "Thrall"),
    Womlings_Support: new WomlingsSupport(
      "Womlings",
      "Womlings_Support",
      "",
      "",
    ),
    Moon_Support: new Support(
      "Moon Support",
      "Moon_Support",
      "space",
      "spc_moon",
    ),
    Red_Support: new Support("Red Support", "Red_Support", "space", "spc_red"),
    Sun_Support: new Support("Sun Support", "Sun_Support", "space", "spc_sun"),
    Belt_Support: new BeltSupport(
      "Belt Support",
      "Belt_Support",
      "space",
      "spc_belt",
    ),
    Titan_Support: new Support(
      "Titan Support",
      "Titan_Support",
      "space",
      "spc_titan",
    ),
    Electrolysis_Support: new ElectrolysisSupport(
      "Electrolysis Plant",
      "Electrolysis_Support",
      "",
      "",
    ),
    Enceladus_Support: new Support(
      "Enceladus Support",
      "Enceladus_Support",
      "space",
      "spc_enceladus",
    ),
    Eris_Support: new Support(
      "Eris Support",
      "Eris_Support",
      "space",
      "spc_eris",
    ),

    Tau_Support: new Support(
      "Tau Ceti Support",
      "Tau_Support",
      "tauceti",
      "tau_home",
    ),
    Tau_Red_Support: new Support(
      "Tau Ceti Red Support",
      "Tau_Red_Support",
      "tauceti",
      "tau_red",
    ),
    Tau_Belt_Support: new Support(
      "Tau Ceti Belt Support",
      "Tau_Belt_Support",
      "tauceti",
      "tau_roid",
    ),

    Alpha_Support: new Support(
      "Alpha Support",
      "Alpha_Support",
      "interstellar",
      "int_alpha",
    ),
    Nebula_Support: new Support(
      "Nebula Support",
      "Nebula_Support",
      "interstellar",
      "int_nebula",
    ),
    Gateway_Support: new Support(
      "Gateway Support",
      "Gateway_Support",
      "galaxy",
      "gxy_gateway",
    ),
    Alien_Support: new Support(
      "Alien Support",
      "Alien_Support",
      "galaxy",
      "gxy_alien2",
    ),
    Lake_Support: new Support(
      "Lake Support",
      "Lake_Support",
      "portal",
      "prtl_lake",
    ),
    Spire_Support: new Support(
      "Spire Support",
      "Spire_Support",
      "portal",
      "prtl_spire",
    ),
    Asphodel_Support: new Support(
      "Asphodel Support",
      "Asphodel_Support",
      "eden",
      "eden_asphodel",
    ),
  };
  // ResourceAction constructors resolve their resource through the entity
  // factory's live outer-catalog getter, matching the original staged init.
  setResources(resources);

  const jobs = {
    Unemployed: new BasicJob("unemployed", "Unemployed"),
    Colonist: new Job("colonist", "Colonist"),
    Teamster: new BasicJob("teamster", "Teamster", { smart: true }),
    Meditator: new BasicJob("meditator", "Meditator", { smart: true }),
    Hunter: new BasicJob("hunter", "Hunter", { serve: true, smart: true }),
    Farmer: new BasicJob("farmer", "Farmer", { serve: true, smart: true }),
    Forager: new BasicJob("forager", "Forager", { serve: true, split: true }),
    Lumberjack: new BasicJob("lumberjack", "Lumberjack", {
      serve: true,
      split: true,
      smart: true,
    }),
    QuarryWorker: new BasicJob("quarry_worker", "Quarry Worker", {
      serve: true,
      split: true,
      smart: true,
    }),
    CrystalMiner: new BasicJob("crystal_miner", "Crystal Miner", {
      serve: true,
      split: true,
      smart: true,
    }),
    Scavenger: new BasicJob("scavenger", "Scavenger", {
      serve: true,
      split: true,
    }),

    TitanColonist: new Job("titan_colonist", "Titan Colonist"),
    Miner: new Job("miner", "Miner", { smart: true }),
    CoalMiner: new Job("coal_miner", "Coal Miner", { smart: true }),
    CementWorker: new Job("cement_worker", "Cement Worker", { smart: true }),
    Professor: new Job("professor", "Professor", { smart: true }),
    Scientist: new Job("scientist", "Scientist", { smart: true }),
    Entertainer: new Job("entertainer", "Entertainer", { smart: true }),
    HellSurveyor: new Job("hell_surveyor", "Hell Surveyor", { smart: true }),
    SpaceMiner: new Job("space_miner", "Space Miner", { smart: true }),
    PitMiner: new Job("pit_miner", "Pit Miner"),
    Torturer: new Job("torturer", "Tormentor", { smart: true }),
    Archaeologist: new Job("archaeologist", "Archaeologist"),
    GhostTrapper: new Job("ghost_trapper", "Ghost Trapper"),
    ElysiumMiner: new Job("elysium_miner", "Elysium Miner"),
    Banker: new Job("banker", "Banker", { smart: true }),
    Priest: new Job("priest", "Priest"),
  };

  // Non-manual crafts should be on top
  const crafter = {
    Scarletite: new CraftingJob(
      "Scarletite",
      "Scarletite Crafter",
      resources.Scarletite,
    ),
    Quantium: new CraftingJob(
      "Quantium",
      "Quantium Crafter",
      resources.Quantium,
    ),
    Plywood: new CraftingJob("Plywood", "Plywood Crafter", resources.Plywood),
    Brick: new CraftingJob("Brick", "Brick Crafter", resources.Brick),
    WroughtIron: new CraftingJob(
      "Wrought_Iron",
      "Wrought Iron Crafter",
      resources.Wrought_Iron,
    ),
    SheetMetal: new CraftingJob(
      "Sheet_Metal",
      "Sheet Metal Crafter",
      resources.Sheet_Metal,
    ),
    Mythril: new CraftingJob("Mythril", "Mythril Crafter", resources.Mythril),
    Aerogel: new CraftingJob("Aerogel", "Aerogel Crafter", resources.Aerogel),
    Nanoweave: new CraftingJob(
      "Nanoweave",
      "Nanoweave Crafter",
      resources.Nanoweave,
    ),
  };

  const buildings = {
    Food: new ResourceAction("Gather Food", "city", "food", "", "Food"),
    Lumber: new ResourceAction("Gather Lumber", "city", "lumber", "", "Lumber"),
    Stone: new ResourceAction("Gather Stone", "city", "stone", "", "Stone"),
    Chrysotile: new ResourceAction(
      "Gather Chrysotile",
      "city",
      "chrysotile",
      "",
      "Chrysotile",
    ),
    Slaughter: new Action("Slaughter the Weak", "city", "slaughter", ""),
    ForgeHorseshoe: new ResourceAction(
      "Horseshoe",
      "city",
      "horseshoe",
      "",
      "Horseshoe",
      { housing: true, garrison: true },
    ),
    SlaveMarket: new ResourceAction(
      "Slave Market",
      "city",
      "slave_market",
      "",
      "Slave",
    ),
    SacrificialAltar: new Action("Sacrificial Altar", "city", "s_alter", ""),
    House: new Action("Cabin", "city", "basic_housing", "", { housing: true }),
    Cottage: new Action("Cottage", "city", "cottage", "", { housing: true }),
    Apartment: new Action("Apartment", "city", "apartment", "", {
      housing: true,
    }),
    Lodge: new Action("Lodge", "city", "lodge", "", { housing: true }),
    Smokehouse: new Action("Smokehouse", "city", "smokehouse", ""),
    SoulWell: new Action("Soul Well", "city", "soul_well", ""),
    SlavePen: new Action("Slave Pen", "city", "slave_pen", ""),
    Transmitter: new Action("Transmitter", "city", "transmitter", "", {
      housing: true,
    }),
    CaptiveHousing: new Action(
      "Captive Housing",
      "city",
      "captive_housing",
      "",
    ),
    Farm: new Action("Farm", "city", "farm", "", { housing: true }),
    CompostHeap: new Action("Compost Heap", "city", "compost", ""),
    Mill: new Action("Windmill", "city", "mill", "", { smart: true }),
    Windmill: new Action("Windmill (Evil)", "city", "windmill", ""),
    Silo: new Action("Grain Silo", "city", "silo", ""),
    Assembly: new ResourceAction(
      "Assembly",
      "city",
      "assembly",
      "",
      "Population",
      { housing: true, important: true },
    ),
    Barracks: new Action("Barracks", "city", "garrison", "", {
      garrison: true,
    }),
    Hospital: new Action("Hospital", "city", "hospital", ""),
    BootCamp: new Action("Boot Camp", "city", "boot_camp", ""),
    Shed: new Action("Shed", "city", "shed", ""),
    StorageYard: new Action("Freight Yard", "city", "storage_yard", ""),
    Warehouse: new Action("Container Port", "city", "warehouse", ""),
    Bank: new Action("Bank", "city", "bank", ""),
    Pylon: new Action("Pylon", "city", "pylon", ""),
    ConcealWard: new Action(
      "Conceal Ward (Witch Hunting)",
      "city",
      "conceal_ward",
      "",
    ),
    Graveyard: new Action("Graveyard", "city", "graveyard", ""),
    LumberYard: new Action("Lumber Yard", "city", "lumber_yard", ""),
    Sawmill: new Action("Sawmill", "city", "sawmill", ""),
    RockQuarry: new Action("Rock Quarry", "city", "rock_quarry", ""),
    CementPlant: new Action("Cement Plant", "city", "cement_plant", "", {
      smart: true,
    }),
    Foundry: new Action("Foundry", "city", "foundry", ""),
    Factory: new Action("Factory", "city", "factory", ""),
    NaniteFactory: new Action("Nanite Factory", "city", "nanite_factory", ""),
    Smelter: new Action("Smelter", "city", "smelter", ""),
    MetalRefinery: new Action("Metal Refinery", "city", "metal_refinery", ""),
    Mine: new Action("Mine", "city", "mine", "", { smart: true }),
    CoalMine: new Action("Coal Mine", "city", "coal_mine", "", { smart: true }),
    OilWell: new Action("Oil Derrick", "city", "oil_well", ""),
    OilDepot: new Action("Fuel Depot", "city", "oil_depot", ""),
    Trade: new Action("Trade Post", "city", "trade", ""),
    Wharf: new Action("Wharf", "city", "wharf", ""),
    TouristCenter: new Action("Tourist Center", "city", "tourist_center", "", {
      smart: true,
    }),
    Amphitheatre: new Action("Amphitheatre", "city", "amphitheatre", ""),
    Casino: new Action("Casino", "city", "casino", ""),
    Temple: new Action("Temple", "city", "temple", ""),
    Shrine: new Action("Shrine", "city", "shrine", ""),
    MeditationChamber: new Action(
      "Meditation Chamber",
      "city",
      "meditation",
      "",
    ),
    Banquet: new Action("Banquet Hall", "city", "banquet", ""),
    University: new Action("University", "city", "university", "", {
      knowledge: true,
    }),
    Library: new Action("Library", "city", "library", "", { knowledge: true }),
    Wardenclyffe: new Action("Wardenclyffe", "city", "wardenclyffe", "", {
      knowledge: true,
    }),
    BioLab: new Action("Bioscience Lab", "city", "biolab", "", {
      knowledge: true,
    }),
    CoalPower: new Action("Coal Powerplant", "city", "coal_power", ""),
    OilPower: new Action("Oil Powerplant", "city", "oil_power", ""),
    FissionPower: new Action("Fission Reactor", "city", "fission_power", ""),
    MassDriver: new Action("Mass Driver", "city", "mass_driver", "", {
      knowledge: () => haveTech("mass", 2),
    }),

    SpaceTestLaunch: new Action(
      "Space Test Launch",
      "space",
      "test_launch",
      "spc_home",
    ),
    SpaceSatellite: new Action(
      "Space Satellite",
      "space",
      "satellite",
      "spc_home",
      { knowledge: true },
    ),
    SpaceGps: new Action("Space Gps", "space", "gps", "spc_home"),
    SpacePropellantDepot: new Action(
      "Space Propellant Depot",
      "space",
      "propellant_depot",
      "spc_home",
    ),
    SpaceNavBeacon: new Action(
      "Space Navigation Beacon",
      "space",
      "nav_beacon",
      "spc_home",
    ),

    MoonMission: new Action(
      "Moon Mission",
      "space",
      "moon_mission",
      "spc_moon",
    ),
    MoonBase: new Action("Moon Base", "space", "moon_base", "spc_moon"),
    MoonIridiumMine: new Action(
      "Moon Iridium Mine",
      "space",
      "iridium_mine",
      "spc_moon",
      { smart: true },
    ),
    MoonHeliumMine: new Action(
      "Moon Helium-3 Mine",
      "space",
      "helium_mine",
      "spc_moon",
      { smart: true },
    ),
    MoonObservatory: new Action(
      "Moon Observatory",
      "space",
      "observatory",
      "spc_moon",
      { knowledge: true },
    ),

    RedMission: new Action("Red Mission", "space", "red_mission", "spc_red"),
    RedSpaceport: new Action("Red Spaceport", "space", "spaceport", "spc_red"),
    RedTower: new Action("Red Space Control", "space", "red_tower", "spc_red"),
    RedCaptiveHousing: new CityAction(
      "Red Captive Housing (Cataclysm)",
      "space",
      "captive_housing",
      "spc_red",
    ),
    RedTerraformer: new Action(
      "Red Terraformer (Orbit Decay)",
      "space",
      "terraformer",
      "spc_red",
      { multiSegmented: true },
    ),
    RedAtmoTerraformer: new Action(
      "Red Terraformer (Orbit Decay, Complete)",
      "space",
      "atmo_terraformer",
      "spc_red",
    ),
    RedTerraform: new Action(
      "Red Terraform (Orbit Decay)",
      "space",
      "terraform",
      "spc_red",
      { prestige: true },
    ),
    RedAssembly: new ResourceAction(
      "Red Assembly (Cataclysm)",
      "space",
      "assembly",
      "spc_red",
      "Population",
      { housing: true, important: true },
    ),
    RedLivingQuarters: new Action(
      "Red Living Quarters",
      "space",
      "living_quarters",
      "spc_red",
      { housing: true },
    ),
    RedPylon: new Action("Red Pylon (Cataclysm)", "space", "pylon", "spc_red"),
    RedVrCenter: new Action("Red VR Center", "space", "vr_center", "spc_red"),
    RedGarage: new Action("Red Garage", "space", "garage", "spc_red"),
    RedMine: new Action("Red Mine", "space", "red_mine", "spc_red"),
    RedFabrication: new Action(
      "Red Fabrication",
      "space",
      "fabrication",
      "spc_red",
    ),
    RedFactory: new Action("Red Factory", "space", "red_factory", "spc_red"),
    RedNaniteFactory: new CityAction(
      "Red Nanite Factory (Cataclysm)",
      "space",
      "nanite_factory",
      "spc_red",
    ),
    RedBiodome: new Action("Red Biodome", "space", "biodome", "spc_red"),
    RedUniversity: new Action(
      "Red University (Orbit Decay)",
      "space",
      "red_university",
      "spc_red",
      { knowledge: true },
    ),
    RedExoticLab: new Action(
      "Red Exotic Materials Lab",
      "space",
      "exotic_lab",
      "spc_red",
      { knowledge: true },
    ),
    RedZiggurat: new Action("Red Ziggurat", "space", "ziggurat", "spc_red"),
    RedSpaceBarracks: new Action(
      "Red Marine Barracks",
      "space",
      "space_barracks",
      "spc_red",
      { garrison: true },
    ),
    RedForgeHorseshoe: new ResourceAction(
      "Red Horseshoe (Cataclysm)",
      "space",
      "horseshoe",
      "spc_red",
      "Horseshoe",
      { housing: true, garrison: true },
    ),

    HellMission: new Action(
      "Hell Mission",
      "space",
      "hell_mission",
      "spc_hell",
    ),
    HellGeothermal: new Action(
      "Hell Geothermal Plant",
      "space",
      "geothermal",
      "spc_hell",
    ),
    HellSmelter: new Action(
      "Hell Smelter",
      "space",
      "hell_smelter",
      "spc_hell",
    ),
    HellSpaceCasino: new Action(
      "Hell Space Casino",
      "space",
      "spc_casino",
      "spc_hell",
    ),
    HellSwarmPlant: new Action(
      "Hell Swarm Plant",
      "space",
      "swarm_plant",
      "spc_hell",
    ),

    SunMission: new Action("Sun Mission", "space", "sun_mission", "spc_sun"),
    SunSwarmControl: new Action(
      "Sun Control Station",
      "space",
      "swarm_control",
      "spc_sun",
    ),
    SunSwarmSatellite: new Action(
      "Sun Swarm Satellite",
      "space",
      "swarm_satellite",
      "spc_sun",
    ),
    SunJumpGate: new Action("Sun Jump Gate", "space", "jump_gate", "spc_sun", {
      multiSegmented: true,
    }),

    GasMission: new Action("Gas Mission", "space", "gas_mission", "spc_gas"),
    GasMining: new Action(
      "Gas Helium-3 Collector",
      "space",
      "gas_mining",
      "spc_gas",
      { smart: true },
    ),
    GasStorage: new Action("Gas Fuel Depot", "space", "gas_storage", "spc_gas"),
    GasSpaceDock: new SpaceDock(
      "Gas Space Dock",
      "space",
      "star_dock",
      "spc_gas",
    ),
    GasSpaceDockProbe: new ModalAction(
      "Space Dock Probe",
      "starDock",
      "probes",
      "",
    ),
    GasSpaceDockGECK: new ModalAction(
      "Space Dock G.E.C.K.",
      "starDock",
      "geck",
      "",
    ),
    GasSpaceDockShipSegment: new ModalAction(
      "Space Dock Bioseeder Ship",
      "starDock",
      "seeder",
      "",
      { multiSegmented: true },
    ),
    GasSpaceDockPrepForLaunch: new ModalAction(
      "Space Dock Prep Ship",
      "starDock",
      "prep_ship",
      "",
    ),
    GasSpaceDockLaunch: new ModalAction(
      "Space Dock Launch Ship",
      "starDock",
      "launch_ship",
      "",
      { prestige: true },
    ),

    GasMoonMission: new Action(
      "Gas Moon Mission",
      "space",
      "gas_moon_mission",
      "spc_gas_moon",
    ),
    GasMoonOutpost: new Action(
      "Gas Moon Mining Outpost",
      "space",
      "outpost",
      "spc_gas_moon",
    ),
    GasMoonDrone: new Action(
      "Gas Moon Mining Drone",
      "space",
      "drone",
      "spc_gas_moon",
    ),
    GasMoonOilExtractor: new Action(
      "Gas Moon Oil Extractor",
      "space",
      "oil_extractor",
      "spc_gas_moon",
      { smart: true },
    ),

    BeltMission: new Action(
      "Belt Mission",
      "space",
      "belt_mission",
      "spc_belt",
    ),
    BeltSpaceStation: new Action(
      "Belt Space Station",
      "space",
      "space_station",
      "spc_belt",
      { smart: true },
    ),
    BeltEleriumShip: new Action(
      "Belt Elerium Mining Ship",
      "space",
      "elerium_ship",
      "spc_belt",
      { smart: true },
    ),
    BeltIridiumShip: new Action(
      "Belt Iridium Mining Ship",
      "space",
      "iridium_ship",
      "spc_belt",
      { smart: true },
    ),
    BeltIronShip: new Action(
      "Belt Iron Mining Ship",
      "space",
      "iron_ship",
      "spc_belt",
      { smart: true },
    ),

    DwarfMission: new Action(
      "Dwarf Mission",
      "space",
      "dwarf_mission",
      "spc_dwarf",
    ),
    DwarfEleriumContainer: new Action(
      "Dwarf Elerium Storage",
      "space",
      "elerium_contain",
      "spc_dwarf",
    ),
    DwarfEleriumReactor: new Action(
      "Dwarf Elerium Reactor",
      "space",
      "e_reactor",
      "spc_dwarf",
    ),
    DwarfWorldCollider: new Action(
      "Dwarf World Collider",
      "space",
      "world_collider",
      "spc_dwarf",
      { multiSegmented: true },
    ),
    DwarfWorldController: new Action(
      "Dwarf World Collider (Complete)",
      "space",
      "world_controller",
      "spc_dwarf",
      { knowledge: true },
    ),
    DwarfShipyard: new Action(
      "Dwarf Ship Yard",
      "space",
      "shipyard",
      "spc_dwarf",
    ),
    DwarfMassRelay: new Action(
      "Dwarf Mass Relay",
      "space",
      "mass_relay",
      "spc_dwarf",
      { multiSegmented: true },
    ),
    DwarfMassRelayComplete: new Action(
      "Dwarf Mass Relay (Complete)",
      "space",
      "m_relay",
      "spc_dwarf",
    ),

    TitanMission: new Action(
      "Titan Mission",
      "space",
      "titan_mission",
      "spc_titan",
    ),
    TitanSpaceport: new Action(
      "Titan Spaceport",
      "space",
      "titan_spaceport",
      "spc_titan",
    ),
    TitanElectrolysis: new Action(
      "Titan Electrolysis",
      "space",
      "electrolysis",
      "spc_titan",
    ),
    TitanHydrogen: new Action(
      "Titan Hydrogen Plant",
      "space",
      "hydrogen_plant",
      "spc_titan",
    ),
    TitanQuarters: new Action(
      "Titan Habitat",
      "space",
      "titan_quarters",
      "spc_titan",
    ),
    TitanMine: new Action("Titan Mine", "space", "titan_mine", "spc_titan"),
    TitanStorehouse: new Action(
      "Titan Storehouse",
      "space",
      "storehouse",
      "spc_titan",
    ),
    TitanBank: new Action("Titan Bank", "space", "titan_bank", "spc_titan"),
    TitanGraphene: new Action(
      "Titan Graphene Plant",
      "space",
      "g_factory",
      "spc_titan",
    ),
    TitanSAM: new Action("Titan SAM Site", "space", "sam", "spc_titan"),
    TitanDecoder: new Action("Titan Decoder", "space", "decoder", "spc_titan"),
    TitanAI: new Action("Titan AI Core", "space", "ai_core", "spc_titan", {
      multiSegmented: true,
    }),
    TitanAIComplete: new Action(
      "Titan AI Core (Complete)",
      "space",
      "ai_core2",
      "spc_titan",
    ),
    TitanAIColonist: new Action(
      "Titan AI Colonist",
      "space",
      "ai_colonist",
      "spc_titan",
    ),
    EnceladusMission: new Action(
      "Enceladus Mission",
      "space",
      "enceladus_mission",
      "spc_enceladus",
    ),
    EnceladusWaterFreighter: new Action(
      "Enceladus Water Freighter",
      "space",
      "water_freighter",
      "spc_enceladus",
      { smart: true },
    ),
    EnceladusZeroGLab: new Action(
      "Enceladus Zero Gravity Lab",
      "space",
      "zero_g_lab",
      "spc_enceladus",
    ),
    EnceladusBase: new Action(
      "Enceladus Operational Base",
      "space",
      "operating_base",
      "spc_enceladus",
    ),
    EnceladusMunitions: new Action(
      "Enceladus Munitions Depot",
      "space",
      "munitions_depot",
      "spc_enceladus",
    ),
    TritonMission: new Action(
      "Triton Mission",
      "space",
      "triton_mission",
      "spc_triton",
    ),
    TritonFOB: new Action("Triton Forward Base", "space", "fob", "spc_triton"),
    TritonLander: new Action(
      "Triton Troop Lander",
      "space",
      "lander",
      "spc_triton",
      { smart: true },
    ),
    TritonCrashedShip: new Action(
      "Triton Derelict Ship",
      "space",
      "crashed_ship",
      "spc_triton",
    ),
    KuiperMission: new Action(
      "Kuiper Mission",
      "space",
      "kuiper_mission",
      "spc_kuiper",
    ),
    KuiperOrichalcum: new Action(
      "Kuiper Orichalcum Mine",
      "space",
      "orichalcum_mine",
      "spc_kuiper",
      { smart: true },
    ),
    KuiperUranium: new Action(
      "Kuiper Uranium Mine",
      "space",
      "uranium_mine",
      "spc_kuiper",
      { smart: true },
    ),
    KuiperNeutronium: new Action(
      "Kuiper Neutronium Mine",
      "space",
      "neutronium_mine",
      "spc_kuiper",
      { smart: true },
    ),
    KuiperElerium: new Action(
      "Kuiper Elerium Mine",
      "space",
      "elerium_mine",
      "spc_kuiper",
      { smart: true },
    ),
    ErisMission: new Action(
      "Eris Mission",
      "space",
      "eris_mission",
      "spc_eris",
    ),
    ErisDrone: new Action(
      "Eris Control Relay",
      "space",
      "drone_control",
      "spc_eris",
    ),
    ErisTrooper: new Action(
      "Eris Android Trooper",
      "space",
      "shock_trooper",
      "spc_eris",
    ),
    ErisTank: new Action("Eris Tank", "space", "tank", "spc_eris"),
    ErisDigsite: new Action("Eris Digsite", "space", "digsite", "spc_eris"),

    TauStarRingworld: new Action(
      "Tau Star Ringworld",
      "tauceti",
      "ringworld",
      "tau_star",
      { multiSegmented: true },
    ),
    TauStarMatrix: new Action(
      "Tau Star Matrix",
      "tauceti",
      "matrix",
      "tau_star",
    ),
    TauStarBluePill: new Action(
      "Tau Star Blue Pill",
      "tauceti",
      "blue_pill",
      "tau_star",
      { prestige: true },
    ),
    TauStarEden: new Action(
      "Tau Star Garden of Eden",
      "tauceti",
      "goe_facility",
      "tau_star",
      { prestige: true },
    ),

    TauMission: new Action(
      "Tau Mission",
      "tauceti",
      "home_mission",
      "tau_home",
    ),
    TauDismantle: new Action(
      "Tau Dismantle Ship",
      "tauceti",
      "dismantle",
      "tau_home",
    ),
    TauOrbitalStation: new Action(
      "Tau Orbital Station",
      "tauceti",
      "orbital_station",
      "tau_home",
    ),
    TauColony: new Action("Tau Colony", "tauceti", "colony", "tau_home", {
      housing: true,
    }),
    TauHousing: new Action(
      "Tau Housing",
      "tauceti",
      "tau_housing",
      "tau_home",
      { housing: true },
    ),
    TauCaptiveHousing: new CityAction(
      "Tau Captive Housing",
      "tauceti",
      "captive_housing",
      "tau_home",
    ),
    TauPylon: new Action("Tau Pylon", "tauceti", "pylon", "tau_home"),
    TauCloning: new ResourceAction(
      "Tau Cloning",
      "tauceti",
      "cloning_facility",
      "tau_home",
      "Population",
      { housing: true },
    ),
    TauForgeHorseshoe: new ResourceAction(
      "Tau Horseshoe",
      "tauceti",
      "horseshoe",
      "tau_home",
      "Horseshoe",
      { housing: true, garrison: true },
    ),
    TauAssembly: new ResourceAction(
      "Tau Assembly",
      "tauceti",
      "assembly",
      "tau_home",
      "Population",
      { housing: true, important: true },
    ),
    TauNaniteFactory: new CityAction(
      "Tau Nanite Factory",
      "tauceti",
      "nanite_factory",
      "tau_home",
    ),
    TauFarm: new Action(
      "Tau High-Tech Farm",
      "tauceti",
      "tau_farm",
      "tau_home",
    ),
    TauMiningPit: new Action(
      "Tau Mining Pit",
      "tauceti",
      "mining_pit",
      "tau_home",
      { smart: true },
    ),
    TauExcavate: new Action("Tau Excavate", "tauceti", "excavate", "tau_home"),
    TauAlienOutpost: new Action(
      "Tau Alien Outpost",
      "tauceti",
      "alien_outpost",
      "tau_home",
      { knowledge: true },
    ),
    TauJumpGate: new Action(
      "Tau Jump Gate",
      "tauceti",
      "jump_gate",
      "tau_home",
      { multiSegmented: true },
    ),
    TauFusionGenerator: new Action(
      "Tau Fusion Generator",
      "tauceti",
      "fusion_generator",
      "tau_home",
    ),
    TauRepository: new Action(
      "Tau Repository",
      "tauceti",
      "repository",
      "tau_home",
    ),
    TauFactory: new Action(
      "Tau High-Tech Factory",
      "tauceti",
      "tau_factory",
      "tau_home",
    ),
    TauDiseaseLab: new Action(
      "Tau Disease Lab",
      "tauceti",
      "infectious_disease_lab",
      "tau_home",
      { knowledge: true },
    ),
    TauCasino: new Action(
      "Tau Casino",
      "tauceti",
      "tauceti_casino",
      "tau_home",
    ),
    TauCulturalCenter: new Action(
      "Tau Cultural Center",
      "tauceti",
      "tau_cultural_center",
      "tau_home",
    ),

    TauRedMission: new Action(
      "Tau Red Mission",
      "tauceti",
      "red_mission",
      "tau_red",
    ),
    TauRedOrbitalPlatform: new Action(
      "Tau Red Orbital Platform",
      "tauceti",
      "orbital_platform",
      "tau_red",
    ),
    TauRedContact: new Action(
      "Tau Red Contact",
      "tauceti",
      "contact",
      "tau_red",
    ),
    TauRedIntroduce: new Action(
      "Tau Red Introduce",
      "tauceti",
      "introduce",
      "tau_red",
    ),
    TauRedSubjugate: new Action(
      "Tau Red Subjugate",
      "tauceti",
      "subjugate",
      "tau_red",
    ),
    TauRedJeff: new Action("Tau Red Jeff", "tauceti", "jeff", "tau_red"),
    TauRedOverseer: new Action(
      "Tau Red Overseer",
      "tauceti",
      "overseer",
      "tau_red",
      { smart: true },
    ),
    TauRedWomlingVillage: new Action(
      "Tau Red Womling Village",
      "tauceti",
      "womling_village",
      "tau_red",
    ),
    TauRedWomlingFarm: new Action(
      "Tau Red Womling Farm",
      "tauceti",
      "womling_farm",
      "tau_red",
      { smart: true },
    ),
    TauRedWomlingMine: new Action(
      "Tau Red Womling Mine",
      "tauceti",
      "womling_mine",
      "tau_red",
      { smart: true },
    ),
    TauRedWomlingFun: new Action(
      "Tau Red Womling Theater",
      "tauceti",
      "womling_fun",
      "tau_red",
      { smart: true },
    ),
    TauRedWomlingLab: new Action(
      "Tau Red Womling Lab",
      "tauceti",
      "womling_lab",
      "tau_red",
      { smart: true, knowledge: true },
    ),

    TauGasContest: new Action(
      "Tau Gas Naming Contest",
      "tauceti",
      "gas_contest",
      "tau_gas",
    ),
    TauGasName1: new Action(
      "Tau Gas Name 1",
      "tauceti",
      "gas_contest-a1",
      "tau_gas",
      { random: true },
    ),
    TauGasName2: new Action(
      "Tau Gas Name 2",
      "tauceti",
      "gas_contest-a2",
      "tau_gas",
      { random: true },
    ),
    TauGasName3: new Action(
      "Tau Gas Name 3",
      "tauceti",
      "gas_contest-a3",
      "tau_gas",
      { random: true },
    ),
    TauGasName4: new Action(
      "Tau Gas Name 4",
      "tauceti",
      "gas_contest-a4",
      "tau_gas",
      { random: true },
    ),
    TauGasName5: new Action(
      "Tau Gas Name 5",
      "tauceti",
      "gas_contest-a5",
      "tau_gas",
      { random: true },
    ),
    TauGasName6: new Action(
      "Tau Gas Name 6",
      "tauceti",
      "gas_contest-a6",
      "tau_gas",
      { random: true },
    ),
    TauGasName7: new Action(
      "Tau Gas Name 7",
      "tauceti",
      "gas_contest-a7",
      "tau_gas",
      { random: true },
    ),
    TauGasName8: new Action(
      "Tau Gas Name 8",
      "tauceti",
      "gas_contest-a8",
      "tau_gas",
      { random: true },
    ),
    TauGasRefuelingStation: new Action(
      "Tau Gas Refueling Station",
      "tauceti",
      "refueling_station",
      "tau_gas",
    ),
    TauGasOreRefinery: new Action(
      "Tau Gas Ore Refinery",
      "tauceti",
      "ore_refinery",
      "tau_gas",
    ),
    TauGasWhalingStation: new Action(
      "Tau Gas Whale Processor",
      "tauceti",
      "whaling_station",
      "tau_gas",
      { smart: true },
    ),
    TauGasWomlingStation: new Action(
      "Tau Gas Womling Station",
      "tauceti",
      "womling_station",
      "tau_gas",
    ),

    TauBeltMission: new Action(
      "Tau Belt Mission",
      "tauceti",
      "roid_mission",
      "tau_roid",
    ),
    TauBeltPatrolShip: new Action(
      "Tau Belt Patrol Ship",
      "tauceti",
      "patrol_ship",
      "tau_roid",
    ),
    TauBeltMiningShip: new Action(
      "Tau Belt Extractor Ship",
      "tauceti",
      "mining_ship",
      "tau_roid",
    ),
    TauBeltWhalingShip: new Action(
      "Tau Belt Whaling Ship",
      "tauceti",
      "whaling_ship",
      "tau_roid",
    ),

    TauGas2Contest: new Action(
      "Tau Gas 2 Naming Contest",
      "tauceti",
      "gas_contest2",
      "tau_gas2",
    ),
    TauGas2Name1: new Action(
      "Tau Gas 2 Name 1",
      "tauceti",
      "gas_contest-b1",
      "tau_gas2",
      { random: true },
    ),
    TauGas2Name2: new Action(
      "Tau Gas 2 Name 2",
      "tauceti",
      "gas_contest-b2",
      "tau_gas2",
      { random: true },
    ),
    TauGas2Name3: new Action(
      "Tau Gas 2 Name 3",
      "tauceti",
      "gas_contest-b3",
      "tau_gas2",
      { random: true },
    ),
    TauGas2Name4: new Action(
      "Tau Gas 2 Name 4",
      "tauceti",
      "gas_contest-b4",
      "tau_gas2",
      { random: true },
    ),
    TauGas2Name5: new Action(
      "Tau Gas 2 Name 5",
      "tauceti",
      "gas_contest-b5",
      "tau_gas2",
      { random: true },
    ),
    TauGas2Name6: new Action(
      "Tau Gas 2 Name 6",
      "tauceti",
      "gas_contest-b6",
      "tau_gas2",
      { random: true },
    ),
    TauGas2Name7: new Action(
      "Tau Gas 2 Name 7",
      "tauceti",
      "gas_contest-b7",
      "tau_gas2",
      { random: true },
    ),
    TauGas2Name8: new Action(
      "Tau Gas 2 Name 8",
      "tauceti",
      "gas_contest-b8",
      "tau_gas2",
      { random: true },
    ),
    TauGas2AlienSurvey: new Action(
      "Tau Gas 2 Alien Station (Survey)",
      "tauceti",
      "alien_station_survey",
      "tau_gas2",
    ),
    TauGas2AlienStation: new Action(
      "Tau Gas 2 Alien Station",
      "tauceti",
      "alien_station",
      "tau_gas2",
      { multiSegmented: true },
    ),
    TauGas2AlienSpaceStation: new Action(
      "Tau Gas 2 Alien Space Station",
      "tauceti",
      "alien_space_station",
      "tau_gas2",
    ),
    TauGas2MatrioshkaBrain: new Action(
      "Tau Gas 2 Matrioshka Brain",
      "tauceti",
      "matrioshka_brain",
      "tau_gas2",
      { multiSegmented: true },
    ),
    TauGas2IgnitionDevice: new Action(
      "Tau Gas 2 Ignition Device",
      "tauceti",
      "ignition_device",
      "tau_gas2",
      { multiSegmented: true },
    ),
    TauGas2IgniteGasGiant: new Action(
      "Tau Gas 2 Ignite Gas Giant",
      "tauceti",
      "ignite_gas_giant",
      "tau_gas2",
      { prestige: true },
    ),

    AlphaMission: new Action(
      "Alpha Centauri Mission",
      "interstellar",
      "alpha_mission",
      "int_alpha",
    ),
    AlphaStarport: new Action(
      "Alpha Starport",
      "interstellar",
      "starport",
      "int_alpha",
    ),
    AlphaHabitat: new Action(
      "Alpha Habitat",
      "interstellar",
      "habitat",
      "int_alpha",
      { housing: true },
    ),
    AlphaMiningDroid: new Action(
      "Alpha Mining Droid",
      "interstellar",
      "mining_droid",
      "int_alpha",
    ),
    AlphaProcessing: new Action(
      "Alpha Processing Facility",
      "interstellar",
      "processing",
      "int_alpha",
    ),
    AlphaFusion: new Action(
      "Alpha Fusion Reactor",
      "interstellar",
      "fusion",
      "int_alpha",
    ),
    AlphaLaboratory: new Action(
      "Alpha Laboratory",
      "interstellar",
      "laboratory",
      "int_alpha",
      { knowledge: true },
    ),
    AlphaExchange: new Action(
      "Alpha Exchange",
      "interstellar",
      "exchange",
      "int_alpha",
    ),
    AlphaGraphenePlant: new Action(
      "Alpha Graphene Plant",
      "interstellar",
      "g_factory",
      "int_alpha",
    ),
    AlphaWarehouse: new Action(
      "Alpha Warehouse",
      "interstellar",
      "warehouse",
      "int_alpha",
    ),
    AlphaMegaFactory: new Action(
      "Alpha Mega Factory",
      "interstellar",
      "int_factory",
      "int_alpha",
    ),
    AlphaLuxuryCondo: new Action(
      "Alpha Luxury Condo",
      "interstellar",
      "luxury_condo",
      "int_alpha",
      { housing: true },
    ),
    AlphaExoticZoo: new Action(
      "Alpha Exotic Zoo",
      "interstellar",
      "zoo",
      "int_alpha",
      { smart: true },
    ),

    ProximaMission: new Action(
      "Proxima Mission",
      "interstellar",
      "proxima_mission",
      "int_proxima",
    ),
    ProximaTransferStation: new Action(
      "Proxima Transfer Station",
      "interstellar",
      "xfer_station",
      "int_proxima",
    ),
    ProximaCargoYard: new Action(
      "Proxima Cargo Yard",
      "interstellar",
      "cargo_yard",
      "int_proxima",
    ),
    ProximaCruiser: new Action(
      "Proxima Patrol Cruiser",
      "interstellar",
      "cruiser",
      "int_proxima",
      { garrison: true },
    ),
    ProximaDyson: new Action(
      "Proxima Dyson Sphere (Adamantite)",
      "interstellar",
      "dyson",
      "int_proxima",
      { multiSegmented: true },
    ),
    ProximaDysonSphere: new Action(
      "Proxima Dyson Sphere (Bolognium)",
      "interstellar",
      "dyson_sphere",
      "int_proxima",
      { multiSegmented: true },
    ),
    ProximaOrichalcumSphere: new Action(
      "Proxima Dyson Sphere (Orichalcum)",
      "interstellar",
      "orichalcum_sphere",
      "int_proxima",
      { multiSegmented: true },
    ),
    ProximaElysaniteSphere: new Action(
      "Proxima Dyson Sphere (Elysanite)",
      "interstellar",
      "elysanite_sphere",
      "int_proxima",
      { multiSegmented: true },
    ),

    NebulaMission: new Action(
      "Nebula Mission",
      "interstellar",
      "nebula_mission",
      "int_nebula",
    ),
    NebulaNexus: new Action(
      "Nebula Nexus",
      "interstellar",
      "nexus",
      "int_nebula",
    ),
    NebulaHarvester: new Action(
      "Nebula Harvester",
      "interstellar",
      "harvester",
      "int_nebula",
      { smart: true },
    ),
    NebulaEleriumProspector: new Action(
      "Nebula Elerium Prospector",
      "interstellar",
      "elerium_prospector",
      "int_nebula",
    ),

    NeutronMission: new Action(
      "Neutron Mission",
      "interstellar",
      "neutron_mission",
      "int_neutron",
    ),
    NeutronMiner: new Action(
      "Neutron Miner",
      "interstellar",
      "neutron_miner",
      "int_neutron",
    ),
    NeutronCitadel: new Action(
      "Neutron Citadel Station",
      "interstellar",
      "citadel",
      "int_neutron",
    ),
    NeutronStellarForge: new Action(
      "Neutron Stellar Forge",
      "interstellar",
      "stellar_forge",
      "int_neutron",
    ),

    Blackhole: new Action(
      "Blackhole Mission",
      "interstellar",
      "blackhole_mission",
      "int_blackhole",
    ),
    BlackholeFarReach: new Action(
      "Blackhole Farpoint",
      "interstellar",
      "far_reach",
      "int_blackhole",
      { knowledge: true },
    ),
    BlackholeStellarEngine: new Action(
      "Blackhole Stellar Engine",
      "interstellar",
      "stellar_engine",
      "int_blackhole",
      { multiSegmented: true },
    ),
    BlackholeMassEjector: new Action(
      "Blackhole Mass Ejector",
      "interstellar",
      "mass_ejector",
      "int_blackhole",
    ),

    BlackholeJumpShip: new Action(
      "Blackhole Jump Ship",
      "interstellar",
      "jump_ship",
      "int_blackhole",
    ),
    BlackholeWormholeMission: new Action(
      "Blackhole Wormhole Mission",
      "interstellar",
      "wormhole_mission",
      "int_blackhole",
    ),
    BlackholeStargate: new Action(
      "Blackhole Stargate",
      "interstellar",
      "stargate",
      "int_blackhole",
      { multiSegmented: true },
    ),
    BlackholeStargateComplete: new Action(
      "Blackhole Stargate (Complete)",
      "interstellar",
      "s_gate",
      "int_blackhole",
    ),

    SiriusMission: new Action(
      "Sirius Mission",
      "interstellar",
      "sirius_mission",
      "int_sirius",
    ),
    SiriusAnalysis: new Action(
      "Sirius B Analysis",
      "interstellar",
      "sirius_b",
      "int_sirius",
    ),
    SiriusSpaceElevator: new Action(
      "Sirius Space Elevator",
      "interstellar",
      "space_elevator",
      "int_sirius",
      { multiSegmented: true },
    ),
    SiriusGravityDome: new Action(
      "Sirius Gravity Dome",
      "interstellar",
      "gravity_dome",
      "int_sirius",
      { multiSegmented: true },
    ),
    SiriusAscensionMachine: new Action(
      "Sirius Ascension Machine",
      "interstellar",
      "ascension_machine",
      "int_sirius",
      { multiSegmented: true },
    ),
    SiriusAscensionTrigger: new Action(
      "Sirius Ascension Machine (Complete)",
      "interstellar",
      "ascension_trigger",
      "int_sirius",
      { smart: true },
    ),
    SiriusAscend: new Action(
      "Sirius Ascend",
      "interstellar",
      "ascend",
      "int_sirius",
      { prestige: true },
    ),
    SiriusThermalCollector: new Action(
      "Sirius Thermal Collector",
      "interstellar",
      "thermal_collector",
      "int_sirius",
    ),

    GatewayMission: new Action(
      "Gateway Mission",
      "galaxy",
      "gateway_mission",
      "gxy_gateway",
    ),
    GatewayStarbase: new Action(
      "Gateway Starbase",
      "galaxy",
      "starbase",
      "gxy_gateway",
      { garrison: true },
    ),
    GatewayShipDock: new Action(
      "Gateway Ship Dock",
      "galaxy",
      "ship_dock",
      "gxy_gateway",
    ),

    BologniumShip: new Action(
      "Gateway Bolognium Ship",
      "galaxy",
      "bolognium_ship",
      "gxy_gateway",
      { ship: true, smart: true },
    ),
    ScoutShip: new Action(
      "Gateway Scout Ship",
      "galaxy",
      "scout_ship",
      "gxy_gateway",
      { ship: true, smart: true },
    ),
    CorvetteShip: new Action(
      "Gateway Corvette Ship",
      "galaxy",
      "corvette_ship",
      "gxy_gateway",
      { ship: true, smart: true },
    ),
    FrigateShip: new Action(
      "Gateway Frigate Ship",
      "galaxy",
      "frigate_ship",
      "gxy_gateway",
      { ship: true },
    ),
    CruiserShip: new Action(
      "Gateway Cruiser Ship",
      "galaxy",
      "cruiser_ship",
      "gxy_gateway",
      { ship: true },
    ),
    Dreadnought: new Action(
      "Gateway Dreadnought",
      "galaxy",
      "dreadnought",
      "gxy_gateway",
      { ship: true },
    ),

    StargateStation: new Action(
      "Stargate Station",
      "galaxy",
      "gateway_station",
      "gxy_stargate",
    ),
    StargateTelemetryBeacon: new Action(
      "Stargate Telemetry Beacon",
      "galaxy",
      "telemetry_beacon",
      "gxy_stargate",
      { knowledge: true },
    ),
    StargateDepot: new Action(
      "Stargate Depot",
      "galaxy",
      "gateway_depot",
      "gxy_stargate",
    ),
    StargateDefensePlatform: new Action(
      "Stargate Defense Platform",
      "galaxy",
      "defense_platform",
      "gxy_stargate",
    ),

    GorddonMission: new Action(
      "Gorddon Mission",
      "galaxy",
      "gorddon_mission",
      "gxy_gorddon",
    ),
    GorddonEmbassy: new Action(
      "Gorddon Embassy",
      "galaxy",
      "embassy",
      "gxy_gorddon",
      { housing: true },
    ),
    GorddonDormitory: new Action(
      "Gorddon Dormitory",
      "galaxy",
      "dormitory",
      "gxy_gorddon",
      { housing: true },
    ),
    GorddonSymposium: new Action(
      "Gorddon Symposium",
      "galaxy",
      "symposium",
      "gxy_gorddon",
      { knowledge: true },
    ),
    GorddonFreighter: new Action(
      "Gorddon Freighter",
      "galaxy",
      "freighter",
      "gxy_gorddon",
      { ship: true },
    ),

    Alien1Consulate: new Action(
      "Alien 1 Consulate",
      "galaxy",
      "consulate",
      "gxy_alien1",
      { housing: true },
    ),
    Alien1Resort: new Action(
      "Alien 1 Resort",
      "galaxy",
      "resort",
      "gxy_alien1",
    ),
    Alien1VitreloyPlant: new Action(
      "Alien 1 Vitreloy Plant",
      "galaxy",
      "vitreloy_plant",
      "gxy_alien1",
      { smart: true },
    ),
    Alien1SuperFreighter: new Action(
      "Alien 1 Super Freighter",
      "galaxy",
      "super_freighter",
      "gxy_alien1",
      { ship: true },
    ),

    Alien2Mission: new Action(
      "Alien 2 Mission",
      "galaxy",
      "alien2_mission",
      "gxy_alien2",
    ),
    Alien2Foothold: new Action(
      "Alien 2 Foothold",
      "galaxy",
      "foothold",
      "gxy_alien2",
    ),
    Alien2ArmedMiner: new Action(
      "Alien 2 Armed Miner",
      "galaxy",
      "armed_miner",
      "gxy_alien2",
      { ship: true, smart: true },
    ),
    Alien2OreProcessor: new Action(
      "Alien 2 Ore Processor",
      "galaxy",
      "ore_processor",
      "gxy_alien2",
    ),
    Alien2Scavenger: new Action(
      "Alien 2 Scavenger",
      "galaxy",
      "scavenger",
      "gxy_alien2",
      { knowledge: true, ship: true },
    ),

    ChthonianMission: new Action(
      "Chthonian Mission",
      "galaxy",
      "chthonian_mission",
      "gxy_chthonian",
    ),
    ChthonianMineLayer: new Action(
      "Chthonian Mine Layer",
      "galaxy",
      "minelayer",
      "gxy_chthonian",
      { ship: true, smart: true },
    ),
    ChthonianExcavator: new Action(
      "Chthonian Excavator",
      "galaxy",
      "excavator",
      "gxy_chthonian",
      { smart: true },
    ),
    ChthonianRaider: new Action(
      "Chthonian Corsair",
      "galaxy",
      "raider",
      "gxy_chthonian",
      { ship: true, smart: true },
    ),

    PortalTurret: new Action(
      "Portal Laser Turret",
      "portal",
      "turret",
      "prtl_fortress",
    ),
    PortalCarport: new Action(
      "Portal Surveyor Carport",
      "portal",
      "carport",
      "prtl_fortress",
    ),
    PortalWarDroid: new Action(
      "Portal War Droid",
      "portal",
      "war_droid",
      "prtl_fortress",
    ),
    PortalRepairDroid: new Action(
      "Portal Repair Droid",
      "portal",
      "repair_droid",
      "prtl_fortress",
    ),

    BadlandsPredatorDrone: new Action(
      "Badlands Predator Drone",
      "portal",
      "war_drone",
      "prtl_badlands",
    ),
    BadlandsSensorDrone: new Action(
      "Badlands Sensor Drone",
      "portal",
      "sensor_drone",
      "prtl_badlands",
    ),
    BadlandsAttractor: new Action(
      "Badlands Attractor Beacon",
      "portal",
      "attractor",
      "prtl_badlands",
      { smart: true },
    ),
    BadlandsMinions: new Action(
      "Badlands Minions Lair (Warlord)",
      "portal",
      "minions",
      "prtl_badlands",
    ),
    BadlandsReaper: new Action(
      "Badlands Soul Reaper (Warlord)",
      "portal",
      "reaper",
      "prtl_badlands",
    ),
    BadlandsCorpsePile: new Action(
      "Badlands Corpse Pile (Warlord)",
      "portal",
      "corpse_pile",
      "prtl_badlands",
    ),
    BadlandsMortuary: new Action(
      "Badlands Mortuary (Warlord)",
      "portal",
      "mortuary",
      "prtl_badlands",
    ),
    BadlandsCodex: new Action(
      "Badlands Create Codex (Warlord)",
      "portal",
      "codex",
      "prtl_badlands",
    ),

    WastelandThrone: new Action(
      "Wasteland Throne of Evil (Warlord)",
      "portal",
      "throne",
      "prtl_wasteland",
    ),
    WastelandIncinerator: new Action(
      "Wasteland Incinerator (Warlord)",
      "portal",
      "incinerator",
      "prtl_wasteland",
    ),
    WastelandWarehouse: new Action(
      "Wasteland Warehouse (Warlord)",
      "portal",
      "warehouse",
      "prtl_wasteland",
    ),
    WastelandHovel: new Action(
      "Wasteland Hellspawn Hovel (Warlord)",
      "portal",
      "hovel",
      "prtl_wasteland",
      { housing: true },
    ),
    WastelandHellCasino: new Action(
      "Wasteland Den of Sin (Warlord)",
      "portal",
      "hell_casino",
      "prtl_wasteland",
    ),
    WastelandTwistedLab: new Action(
      "Wasteland Twisted Lab (Warlord)",
      "portal",
      "twisted_lab",
      "prtl_wasteland",
      { knowledge: true },
    ),
    WastelandDemonForge: new Action(
      "Wasteland Demon Forge (Warlord)",
      "portal",
      "demon_forge",
      "prtl_wasteland",
    ),
    WastelandHellFactory: new Action(
      "Wasteland Terror Factory (Warlord)",
      "portal",
      "hell_factory",
      "prtl_wasteland",
    ),
    WastelandPumpjack: new Action(
      "Wasteland Hellish Pumpjack (Warlord)",
      "portal",
      "pumpjack",
      "prtl_wasteland",
    ),
    WastelandDigDemon: new Action(
      "Wasteland Dig Demon Burrow (Warlord)",
      "portal",
      "dig_demon",
      "prtl_wasteland",
    ),
    WastelandTunneler: new Action(
      "Wasteland Tunneler Demon (Warlord)",
      "portal",
      "tunneler",
      "prtl_wasteland",
    ),
    WastelandBrute: new Action(
      "Wasteland Brute Hut (Warlord)",
      "portal",
      "brute",
      "prtl_wasteland",
      { garrison: true },
    ),
    WastelandAltar: new CityAction(
      "Wasteland Sacrificial Altar (Warlord)",
      "portal",
      "s_alter",
      "prtl_wasteland",
    ),
    WastelandShrine: new CityAction(
      "Wasteland Shrine (Warlord)",
      "portal",
      "shrine",
      "prtl_wasteland",
    ),
    WastelandMeditationChamber: new CityAction(
      "Wasteland Meditation Chamber (Warlord)",
      "portal",
      "meditation",
      "prtl_wasteland",
    ),

    PitMission: new Action("Pit Mission", "portal", "pit_mission", "prtl_pit"),
    PitAssaultForge: new Action(
      "Pit Assault Forge",
      "portal",
      "assault_forge",
      "prtl_pit",
    ),
    PitSoulForge: new Action(
      "Pit Soul Forge",
      "portal",
      "soul_forge",
      "prtl_pit",
    ),
    PitGunEmplacement: new Action(
      "Pit Gun Emplacement",
      "portal",
      "gun_emplacement",
      "prtl_pit",
    ),
    PitSoulAttractor: new Action(
      "Pit Soul Attractor",
      "portal",
      "soul_attractor",
      "prtl_pit",
    ),
    PitSoulCapacitor: new Action(
      "Pit Soul Capacitor (Witch Hunting)",
      "portal",
      "soul_capacitor",
      "prtl_pit",
    ),
    PitAbsorptionChamber: new Action(
      "Pit Absorption Chamber (Witch Hunting)",
      "portal",
      "absorption_chamber",
      "prtl_pit",
    ),
    PitShadowMine: new Action(
      "Pit Shadow Mine (Warlord)",
      "portal",
      "shadow_mine",
      "prtl_pit",
    ),
    PitTavern: new Action(
      "Pit Tavern (Warlord)",
      "portal",
      "tavern",
      "prtl_pit",
    ),

    RuinsMission: new Action(
      "Ruins Mission",
      "portal",
      "ruins_mission",
      "prtl_ruins",
    ),
    RuinsGuardPost: new Action(
      "Ruins Guard Post",
      "portal",
      "guard_post",
      "prtl_ruins",
      { smart: true },
    ),
    RuinsVault: new Action("Ruins Vault", "portal", "vault", "prtl_ruins"),
    RuinsWarVault: new Action(
      "Ruins Vault (Warlord)",
      "portal",
      "war_vault",
      "prtl_ruins",
    ),
    RuinsArchaeology: new Action(
      "Ruins Archaeology",
      "portal",
      "archaeology",
      "prtl_ruins",
    ),
    RuinsArcology: new Action(
      "Ruins Arcology",
      "portal",
      "arcology",
      "prtl_ruins",
    ),
    RuinsHellForge: new Action(
      "Ruins Infernal Forge",
      "portal",
      "hell_forge",
      "prtl_ruins",
    ),
    RuinsInfernoPower: new Action(
      "Ruins Inferno Reactor",
      "portal",
      "inferno_power",
      "prtl_ruins",
    ),
    RuinsAncientPillars: new Pillar(
      "Ruins Ancient Pillars",
      "portal",
      "ancient_pillars",
      "prtl_ruins",
    ),

    GateMission: new Action(
      "Gate Mission",
      "portal",
      "gate_mission",
      "prtl_gate",
    ),
    GateEastTower: new Action(
      "Gate East Tower",
      "portal",
      "east_tower",
      "prtl_gate",
      { multiSegmented: true },
    ),
    GateWestTower: new Action(
      "Gate West Tower",
      "portal",
      "west_tower",
      "prtl_gate",
      { multiSegmented: true },
    ),
    GateTurret: new Action("Gate Turret", "portal", "gate_turret", "prtl_gate"),
    GateInferniteMine: new Action(
      "Gate Infernite Mine",
      "portal",
      "infernite_mine",
      "prtl_gate",
    ),

    LakeMission: new Action(
      "Lake Mission",
      "portal",
      "lake_mission",
      "prtl_lake",
    ),
    LakeHarbor: new Action("Lake Harbor", "portal", "harbor", "prtl_lake", {
      smart: true,
    }),
    LakeCoolingTower: new Action(
      "Lake Cooling Tower",
      "portal",
      "cooling_tower",
      "prtl_lake",
      { smart: true },
    ),
    LakeBireme: new Action(
      "Lake Bireme Warship",
      "portal",
      "bireme",
      "prtl_lake",
      { smart: true },
    ),
    LakeTransport: new Action(
      "Lake Transport",
      "portal",
      "transport",
      "prtl_lake",
      { smart: true },
    ),
    LakeOven: new Action(
      "Lake Cooker (Fasting)",
      "portal",
      "oven",
      "prtl_lake",
    ),
    LakeOvenComplete: new Action(
      "Lake Cooker (Fasting, Complete)",
      "portal",
      "oven_complete",
      "prtl_lake",
    ),
    LakeSoulSteeper: new Action(
      "Lake Soul Steeper (Fasting)",
      "portal",
      "dish_soul_steeper",
      "prtl_lake",
    ),
    LakeLifeInfuser: new Action(
      "Lake Life Infuser (Fasting)",
      "portal",
      "dish_life_infuser",
      "prtl_lake",
    ),
    LakeDevilishDish: new Action(
      "Lake Devilish Dish (Fasting)",
      "portal",
      "devilish_dish",
      "prtl_lake",
    ),

    SpireMission: new Action(
      "Spire Mission",
      "portal",
      "spire_mission",
      "prtl_spire",
    ),
    SpirePurifier: new Action(
      "Spire Purifier",
      "portal",
      "purifier",
      "prtl_spire",
      { smart: true },
    ),
    SpirePort: new Action("Spire Port", "portal", "port", "prtl_spire", {
      smart: true,
    }),
    SpireBaseCamp: new Action(
      "Spire Base Camp",
      "portal",
      "base_camp",
      "prtl_spire",
      { smart: true },
    ),
    SpireBridge: new Action("Spire Bridge", "portal", "bridge", "prtl_spire"),
    SpireSphinx: new Action("Spire Sphinx", "portal", "sphinx", "prtl_spire"),
    SpireBribeSphinx: new Action(
      "Spire Bribe Sphinx",
      "portal",
      "bribe_sphinx",
      "prtl_spire",
    ),
    SpireSurveyTower: new Action(
      "Spire Survey Tower",
      "portal",
      "spire_survey",
      "prtl_spire",
    ),
    SpireMechBay: new Action(
      "Spire Mech Bay",
      "portal",
      "mechbay",
      "prtl_spire",
      { smart: true },
    ),
    SpireTower: new Action("Spire Tower", "portal", "spire", "prtl_spire"),
    SpireWaygate: new Action(
      "Spire Waygate",
      "portal",
      "waygate",
      "prtl_spire",
      { smart: true },
    ),
    SpireEdenicGate: new Action(
      "Spire Edenic Gate",
      "portal",
      "edenic_gate",
      "prtl_spire",
    ),
    SpireBazaar: new Action(
      "Spire Bazaar (Warlord)",
      "portal",
      "bazaar",
      "prtl_spire",
    ),

    AsphodelMission: new Action(
      "Asphodel Mission",
      "eden",
      "survery_meadows",
      "eden_asphodel",
    ),
    AsphodelEncampment: new Action(
      "Asphodel Encampment",
      "eden",
      "encampment",
      "eden_asphodel",
    ),
    AsphodelSoulEngine: new Action(
      "Asphodel Soul Engine",
      "eden",
      "soul_engine",
      "eden_asphodel",
    ),
    AsphodelMechStation: new Action(
      "Asphodel Mech Station",
      "eden",
      "mech_station",
      "eden_asphodel",
      { multiSegmented: true },
    ),
    AsphodelHarvester: new Action(
      "Asphodel Harvester",
      "eden",
      "asphodel_harvester",
      "eden_asphodel",
      { smart: true },
    ),
    AsphodelProcessor: new Action(
      "Asphodel Muon Processor",
      "eden",
      "ectoplasm_processor",
      "eden_asphodel",
    ),
    AsphodelResearchStation: new Action(
      "Asphodel Research Station",
      "eden",
      "research_station",
      "eden_asphodel",
    ),
    AsphodelWarehouse: new Action(
      "Asphodel Warehouse",
      "eden",
      "warehouse",
      "eden_asphodel",
    ),
    AsphodelStabilizer: new Action(
      "Asphodel Stabilizer",
      "eden",
      "stabilizer",
      "eden_asphodel",
    ),
    AsphodelRuneGate: new Action(
      "Asphodel Rune Gate",
      "eden",
      "rune_gate",
      "eden_asphodel",
      { multiSegmented: true },
    ),
    AsphodelRuneGateOpen: new Action(
      "Asphodel Rune Gate (Complete)",
      "eden",
      "rune_gate_open",
      "eden_asphodel",
    ),
    AsphodelBunker: new Action(
      "Asphodel Bunker",
      "eden",
      "bunker",
      "eden_asphodel",
      { garrison: true },
    ),
    AsphodelBlissDen: new Action(
      "Asphodel Bliss Den",
      "eden",
      "bliss_den",
      "eden_asphodel",
    ),
    AsphodelRectory: new Action(
      "Asphodel Rectory",
      "eden",
      "rectory",
      "eden_asphodel",
      { housing: true },
    ),
    AsphodelCorruptor: new Action(
      "Asphodel Corruptor (Warlord)",
      "eden",
      "corruptor",
      "eden_asphodel",
    ),

    ElysiumMission: new Action(
      "Elysium Mission",
      "eden",
      "survey_fields",
      "eden_elysium",
    ),
    ElysiumFortress: new Action(
      "Elysium Celestial Fortress",
      "eden",
      "fortress",
      "eden_elysium",
    ),
    ElysiumSiege: new Action(
      "Elysium Siege Fortress",
      "eden",
      "siege_fortress",
      "eden_elysium",
    ),
    ElysiumRaid: new Action(
      "Elysium Raid Supplies",
      "eden",
      "raid_supplies",
      "eden_elysium",
    ),
    ElysiumAmbush: new Action(
      "Elysium Ambush Patrol",
      "eden",
      "ambush_patrol",
      "eden_elysium",
    ),
    ElysiumRuinedFortress: new Action(
      "Elysium Ruined Fortress",
      "eden",
      "ruined_fortress",
      "eden_elysium",
    ),
    ElysiumScout: new Action(
      "Elysium Scout",
      "eden",
      "scout_elysium",
      "eden_elysium",
    ),
    ElysiumFireSupportBase: new Action(
      "Elysium Fire Support Base",
      "eden",
      "fire_support_base",
      "eden_elysium",
      { multiSegmented: true },
    ),
    ElysiumMine: new Action(
      "Elysium Mine",
      "eden",
      "elysanite_mine",
      "eden_elysium",
    ),
    ElysiumSacredSmelter: new Action(
      "Elysium Sacred Smelter",
      "eden",
      "sacred_smelter",
      "eden_elysium",
    ),
    ElysiumEleriumContainment: new Action(
      "Elysium Elerium Containment",
      "eden",
      "elerium_containment",
      "eden_elysium",
    ),
    ElysiumPillbox: new Action(
      "Elysium Pillbox",
      "eden",
      "pillbox",
      "eden_elysium",
    ), // TODO: Need some interaction with autoHell
    ElysiumRestaurant: new Action(
      "Elysium Restaurant",
      "eden",
      "restaurant",
      "eden_elysium",
    ),
    ElysiumEternalBank: new Action(
      "Elysium Eternal Bank",
      "eden",
      "eternal_bank",
      "eden_elysium",
    ),
    ElysiumArchive: new Action(
      "Elysium Archive",
      "eden",
      "archive",
      "eden_elysium",
    ),
    ElysiumNorthPier: new Action(
      "Elysium North Pier",
      "eden",
      "north_pier",
      "eden_elysium",
      { multiSegmented: true },
    ),
    ElysiumRushmore: new Action(
      "Elysium Rushmore",
      "eden",
      "rushmore",
      "eden_elysium",
    ),
    ElysiumReincarnation: new Action(
      "Elysium Reincarnation",
      "eden",
      "reincarnation",
      "eden_elysium",
    ),
    ElysiumCement: new Action(
      "Elysium Cement",
      "eden",
      "eden_cement",
      "eden_elysium",
    ),

    IsleSouthPier: new Action(
      "Isle South Pier",
      "eden",
      "south_pier",
      "eden_isle",
      { multiSegmented: true },
    ),
    IsleWestTower: new Action(
      "Isle West Tower",
      "eden",
      "west_tower",
      "eden_isle",
    ),
    IsleGarrison: new Action(
      "Isle Garrison",
      "eden",
      "isle_garrison",
      "eden_isle",
    ),
    IsleEastTower: new Action(
      "Isle East Tower",
      "eden",
      "east_tower",
      "eden_isle",
    ),
    IsleSpiritVacuum: new Action(
      "Isle Spirit Vacuum",
      "eden",
      "spirit_vacuum",
      "eden_isle",
    ),
    IsleSpiritBattery: new Action(
      "Isle Spirit Battery",
      "eden",
      "spirit_battery",
      "eden_isle",
    ),
    IsleSoulCompactor: new Action(
      "Isle Soul Compactor",
      "eden",
      "soul_compactor",
      "eden_isle",
    ),

    PalaceMission: new Action(
      "Palace Mission",
      "eden",
      "scout_palace",
      "eden_palace",
    ),
    PalaceThrone: new Action("Palace Throne", "eden", "throne", "eden_palace"),
    PalaceInfuser: new Action(
      "Palace Infuser",
      "eden",
      "infuser",
      "eden_palace",
      { multiSegmented: true },
    ),
    PalaceApotheosis: new Action(
      "Palace Apotheosis",
      "eden",
      "apotheosis",
      "eden_palace",
      { prestige: true },
    ),
    PalaceConduit: new Action(
      "Palace Conduit",
      "eden",
      "conduit",
      "eden_palace",
      { multiSegmented: true },
    ),
    PalaceTomb: new Action("Palace Tomb", "eden", "tomb", "eden_palace", {
      multiSegmented: true,
    }),
  };

  // The catalog key is the stable building identity typed policies compare by,
  // and nothing on the wrapper itself carries it. Projects are deliberately not
  // stamped: they share the weighting phase's target lists with buildings, and
  // an unstamped project can never collide with a building key there.
  for (const [key, building] of Object.entries(buildings)) {
    building.catalogKey = key;
  }

  const linkedBuildings = [
    [buildings.LakeTransport, buildings.LakeBireme],
    [buildings.SpirePort, buildings.SpireBaseCamp],
  ];

  const projects = {
    LaunchFacility: new Project("Launch Facility", "launch_facility"),
    SuperCollider: new Project("Supercollider", "lhc"),
    StockExchange: new Project("Stock Exchange", "stock_exchange"),
    Monument: new Project("Monument", "monument"),
    Railway: new Project("Railway", "railway"),
    Nexus: new Project("Nexus", "nexus"),
    RoidEject: new Project("Asteroid Redirect", "roid_eject"),
    ManaSyphon: new Project("Mana Syphon", "syphon"),
    Depot: new Project("Depot", "tp_depot"),
  };
  return { resources, jobs, crafter, buildings, linkedBuildings, projects };
}
