import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

import * as esbuild from "esbuild";

const root = path.dirname(fileURLToPath(import.meta.url));
const metadataPath = path.join(root, "src", "userscript.meta.js");
const metadataOutputPath = path.join(root, "evolve_automation.meta.js");
const userscriptOutputPath = path.join(root, "evolve_automation.user.js");
const watch = process.argv.includes("--watch");

const metadata = (await readFile(metadataPath, "utf8")).trimEnd();
if (
  !metadata.startsWith("// ==UserScript==") ||
  !metadata.endsWith("// ==/UserScript==")
) {
  throw new Error(`${metadataPath} is not a complete userscript metadata block`);
}

const buildOptions = {
  absWorkingDir: root,
  entryPoints: ["src/main.js"],
  outfile: userscriptOutputPath,
  bundle: true,
  banner: {
    js: `${metadata}\n\n// Generated by npm run build. Edit files under src/ instead.`,
  },
  charset: "utf8",
  format: "iife",
  legalComments: "inline",
  logLevel: "info",
  platform: "browser",
  target: ["esnext"],
  treeShaking: false,
};

if (watch) {
  await writeFile(metadataOutputPath, `${metadata}\n`, "utf8");
  const context = await esbuild.context(buildOptions);
  await context.watch();
  console.log("Watching src/**/*.{js,ts}; press Ctrl+C to stop.");
} else {
  await esbuild.build(buildOptions);
  await writeFile(metadataOutputPath, `${metadata}\n`, "utf8");
}
