import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

import * as esbuild from "esbuild";

const root = path.dirname(fileURLToPath(import.meta.url));
const metadataPath = path.join(root, "src", "userscript.meta.js");
const local = process.argv.includes("--local");
const outputDirectory = local
  ? path.join(root, "test-artifacts", "local")
  : root;
const metadataOutputPath = path.join(
  outputDirectory,
  local ? "evolve_automation.local.meta.js" : "evolve_automation.meta.js",
);
const userscriptOutputPath = path.join(
  outputDirectory,
  local ? "evolve_automation.local.user.js" : "evolve_automation.user.js",
);
const watch = process.argv.includes("--watch");

const sourceMetadata = (await readFile(metadataPath, "utf8")).trimEnd();
const metadata = local
  ? sourceMetadata
      .replace(
        /^\/\/ @name\s+.*$/m,
        "// @name         Evolve Automation (DeadSpace local)",
      )
      .replace(
        /^\/\/ @namespace\s+.*$/m,
        "// @namespace    http://localhost/evolve-automation",
      )
      .replace(/^\/\/ @downloadURL.*\r?\n/m, "")
      .replace(/^\/\/ @updateURL.*\r?\n/m, "")
      .replace(
        /^\/\/ @match\s+.*$/m,
        "// @match        http://localhost:4400/*",
      )
  : sourceMetadata;
if (
  !metadata.startsWith("// ==UserScript==") ||
  !metadata.endsWith("// ==/UserScript==")
) {
  throw new Error(
    `${metadataPath} is not a complete userscript metadata block`,
  );
}

await mkdir(outputDirectory, { recursive: true });

const buildOptions = {
  absWorkingDir: root,
  entryPoints: ["src/main.ts"],
  outfile: userscriptOutputPath,
  bundle: true,
  banner: {
    js: `${metadata}\n\n// Generated by npm run build. Edit files under src/ instead.`,
  },
  charset: "utf8",
  format: "iife",
  legalComments: "inline",
  logLevel: "info",
  platform: "browser",
  target: ["esnext"],
  define: {
    "globalThis.__EA_TEST_SURFACE_ENABLED__": "false",
  },
  minifySyntax: true,
  treeShaking: true,
};

if (watch) {
  await writeFile(metadataOutputPath, `${metadata}\n`, "utf8");
  const context = await esbuild.context(buildOptions);
  await context.watch();
  console.log("Watching src/**/*.{js,ts}; press Ctrl+C to stop.");
} else {
  await esbuild.build(buildOptions);
  await writeFile(metadataOutputPath, `${metadata}\n`, "utf8");
}
